//Organisation Types

//Load Organisation Groups
export const FETCH_ORG_GROUPS = 'FETCH_ORG_GROUPS';
export const SET_ORG_GROUPS = 'SET_ORG_GROUPS';
export const ORG_GROUPS_ERROR = 'ORG_GROUPS_ERROR';

export const CREATE_ORG_GROUP_REQUEST = 'CREATE_ORG_GROUP';
export const CREATE_ORG_GROUP_SUCCESS = 'CREATE_ORG_GROUP_SUCCESS';
export const CREATE_ORG_GROUP_FAIL = 'CREATE_ORG_GROUP_FAIL';
